<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-linearalgebra-nupur-sehgal/blob/main/linear_algebra_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Assignment

**Instructions:**
- Read each question carefully before answering.
- For **written/conceptual** questions, double-click the answer cell below the question and type your response.
- For **coding** questions, write your solution in the code cell provided.
- Run all code cells before submitting — make sure there are no errors.
- When done, click **"Save in GitHub to keep changes"** at the top to submit.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [1]:
# Run this cell before starting — do not modify
import numpy as np

---
## Q2 — Matrix Transformations

You are given the following matrix:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And the following vectors:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Geometric Interpretation

**Without running any code**, predict what happens when you multiply matrix `A` by each of the vectors above.
Explain **geometrically** what the matrix is doing to each vector — not just what the numbers become.

The first column of the matrix A represents how i hat direction and the second column how j hat direction gets linearly transformed. The vectors when multiplied with this matrix will result in a new vector which would be a linear transformation undergone by them due to multiplication with this matrix.

### Q2 Part (ii) — Respond to a Classmate

A classmate says:
> *"Matrix multiplication is just a complicated way to multiply numbers — it doesn't mean anything visually."*

Using your results from Part (i), write **3–4 sentences** proving them wrong.

No matrix multiplicatoin is not just a complicated way to multiply numbers. Here the multiplication of Matrix A with the vectors given result in a new vector. This can be viewed as a linear transformation, where the input is a vector and the output another vector which gets linearly transformed by the action of multiplying matrix A with it.

### Q2 Part (iii) — NumPy Function

Write a NumPy function that:
- Takes **any 2×2 matrix** and **any 2D vector** as inputs
- Returns the **transformed vector**
- Prints a **one-line description** of how the x and y components individually change

Test your function on matrix `A` and all four vectors above.

In [2]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [6]:
# Write your code here:
def transform_vector(matrix, vector):
    transformed = matrix @ vector

    print(f"Original vector: {vector}")
    print(f"Transformed vector: {transformed}")
    print(f"x changes from {vector[0]} to {transformed[0]}, "
          f"y changes from {vector[1]} to {transformed[1]}")
    print()

    return transformed


# Testing all vectors
transform_vector(A, v1)
transform_vector(A, v2)
transform_vector(A, v3)
transform_vector(A, v4)


Original vector: [1 0]
Transformed vector: [2 0]
x changes from 1 to 2, y changes from 0 to 0

Original vector: [0 1]
Transformed vector: [0 3]
x changes from 0 to 0, y changes from 1 to 3

Original vector: [1 1]
Transformed vector: [2 3]
x changes from 1 to 2, y changes from 1 to 3

Original vector: [-2  4]
Transformed vector: [-4 12]
x changes from -2 to -4, y changes from 4 to 12



array([-4, 12])

---
## Q3 — Tiny Recommendation System

Each user's taste is represented as a vector of 4 scores across 4 genres — **action, romance, thriller, comedy** — all between 0 and 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — Similarity Matrix

Compute the **full similarity matrix** — every user's similarity score against every other user — using only a **single NumPy operation** (no loops).

What linear algebra concept makes this possible in one line?

In [7]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [8]:
# Write your code here:
similarity_matrix = users @ users.T
print(similarity_matrix)

[[1.5  0.5  1.48 1.  ]
 [0.5  1.5  0.52 1.  ]
 [1.48 0.52 1.5  1.  ]
 [1.   1.   1.   1.  ]]


**What linear algebra concept makes this possible in one line?**


Matrix multiplication helps to calculate pairwise dot products between vectors simultaneously, which allows all user similarities to be calculated in one operation.

### Q3 Part (ii) — Reason About User D

User D has **equal scores** across all genres.

Before computing anything, reason through: will User D's similarity score with every other user be identical? **Why or why not?** Then verify with code.

Yes user's D similarity score will be identical with every other user as the dot product of D with A, then B, then C will be equal. The dot prodduct depends on the total sum of the product of scores of each genre and here the sum comes same.
In the code the last line gives the User D's similarity score with every other user and it comes out to be same for everyone.

In [9]:
similarity_matrix = users @ users.T
print(similarity_matrix)


[[1.5  0.5  1.48 1.  ]
 [0.5  1.5  0.52 1.  ]
 [1.48 0.52 1.5  1.  ]
 [1.   1.   1.   1.  ]]


### Q3 Part (iii) — The Problem with Raw Dot Products

A senior engineer tells you:
> *"Raw dot products are a bad measure of similarity — you need to normalize."\*

1. What is the **problem** with raw dot products?
2. Construct a **specific example using NumPy** that demonstrates the flaw.
3. Fix it.

> **Hint:** Take a user with scores `[1.8, 0.2, 1.6, 0.4]`

The problem with raw dot products is that they measure both direction similarity and vector magnitude. So a user with larger scores can appear more similar even if their preferences are just scaled up versions of another user.
For example-
A=[0.9, 0.1, 0.8, 0.2]
E=[1.8, 0.2, 1.6, 0.4]
A @ E = 3.0
This score is much larger than A @ A = 1.5, even though E has exactly the same taste pattern as A, just doubled in magnitude.

In [15]:
# Write your code here:
import numpy as np

# Original user
A = np.array([0.9, 0.1, 0.8, 0.2])

# Same taste pattern, but scaled up
E = np.array([1.8, 0.2, 1.6, 0.4])

# Raw dot product
raw_similarity = A @ E

print(round (raw_similarity, 2))
cosine_similarity = (A @ E) / (np.linalg.norm(A) * np.linalg.norm(E))
print("Cosine similarity:", cosine_similarity)

3.0
Cosine similarity: 1.0


### Q3 Part (iv) — Most Similar Users

After normalizing, which **two users are most similar**?

Does that match your intuition from just reading the vectors?

What does it mean in plain language — what do these two users have in common?

> **Note:** A similarity score is just a number that tells you **how alike two things are**.

The most similar users are User A and User C. Their preference vectors are very close, both strongly favoring action and thriller and disliking romance and comedy. In plain terms, they have almost the same taste in genres.

In [18]:
# Write your code here:

# dot product matrix
dot_product = users @ users.T

# norms of each user
norms = np.linalg.norm(users, axis=1)

# outer product of norms
norm_matrix = np.outer(norms, norms)

# cosine similarity matrix
cosine_sim_matrix = dot_product / norm_matrix

print(cosine_sim_matrix)

[[1.         0.33333333 0.98666667 0.81649658]
 [0.33333333 1.         0.34666667 0.81649658]
 [0.98666667 0.34666667 1.         0.81649658]
 [0.81649658 0.81649658 0.81649658 1.        ]]


---

## 🎉 Submission Complete!

Make sure all code cells are run and all written answers are filled in, then click **"Save in GitHub to keep changes"** at the top.